return {
--宠物
	"critter_kitten",
	"critter_puppy",
	"critter_lamb",
	"critter_perdling",
	"critter_dragonling",
	"critter_glomling",
	"critter_lunarmothling",
	"wobysmall",
--随从
	"wobybig",
	"chester",
	"hutch",
	"glommer",
	"lavae_pet",
	"friendlyfruitfly",
--召唤物
	"abigail",
	"shadowduelist",
	"shadowminer",
	"shadowlumber",
	"shadowdigger",
}