return {
	["food"] = {},
	["seeds"] = {},
	["equip"] = {},
	["tool"] = {},
	["magic"] = {},
	["animal"] = {},
	["boss"] = {},
	["follower"] = {},
	["material"] = {},
	["gift"] = {},
	["ruins"] = {},
	["event"] = {},
	["cooking"] = {},
	["props"] = {},
	["clothes"] = {},
	["puppet"] = {},
	["base"] = {},
	["plant"] = {},
	["ore"] = {},
	["den"] = {},
	["building"] = {},
	["sculpture"] = {},
	["natural"] = {},
	["rot"] = {},
}