return {
--石化树
	"rock_petrified_tree_short",
	"rock_petrified_tree_med",
	"rock_petrified_tree_tall",
	"rock_petrified_tree_old",
	"rock_petrified_tree",
--大理石树
	"marbletree",
	"marbletree_1",
	"marbletree_2",
	"marbletree_3",
	"marbletree_4",
--大理石灌木
	"marblebean_sapling",
	"marbleshrub",
	"marbleshrub_short",
	"marbleshrub_normal",
	"marbleshrub_tall",
--卵石
	"rock1",
	"rock2",
	"rock_flintless",
	"rock_flintless_med",
	"rock_flintless_low",
--冰矿
	"rock_ice",
--月岩
	"rock_moon",
	"rock_moon_shell",
	"moonglass_rock",
	"moonrock_pieces",
	"gargoyle_houndatk",
	"gargoyle_hounddeath",
	"gargoyle_werepigatk",
	"gargoyle_werepigdeath",
	"gargoyle_werepighowl",
--古代矿石
	"rubble",
	"rubble_med",
	"rubble_low",
--海上矿石
	"seastack",
	"saltstack",
--石笋
	"stalagmite_low",
	"stalagmite_med",
	"stalagmite_full",
	"stalagmite",
	"stalagmite_tall_low",
	"stalagmite_tall_med",
	"stalagmite_tall_full",
	"stalagmite_tall",
--蛛网岩
	"spiderhole_rock",
--海洋打捞
	"shell_cluster",
	"sunkenchest",
}