return {
    --农作物种子
    "asparagus_seeds",
    "carrot_seeds",
    "corn_seeds",
    "eggplant_seeds",
    "garlic_seeds",
    "onion_seeds",
    "pepper_seeds",
    "potato_seeds",
    "pumpkin_seeds",
    "tomato_seeds",
    "dragonfruit_seeds",
    "durian_seeds",
    "pomegranate_seeds",
    "watermelon_seeds",
    "seeds",
    --蘑菇
    "red_cap",
    "spore_medium",
    "green_cap",
    "spore_small",
    "blue_cap",
    "spore_tall",
    --食人花
    "lureplantbulb",
    --树种
    "marblebean",
    "livingtree_root",
    "twiggy_nut",
    "acorn",
    "pinecone",
    "moonbutterfly",
    --花种
    "butterfly",
    --移植
    "dug_berrybush",
    "dug_berrybush2",
    "dug_berrybush_juicy",
    "dug_grass",
    "dug_sapling",
    "dug_sapling_moon",
    "dug_marsh_bush",
    "dug_rock_avocado_bush",
    "rock_avocado_fruit_sprout",
    "bullkelp_root",
    --藤壶
    "waterplant_planter"
}
