return {
--装饰
	"atrium_fence",
	"atrium_light_back",
	"insanityrock",
--建筑
	"archive_security_desk",
	"archive_orchestrina_main",
	"archive_portal",
	"archive_cookpot",
	"archive_lockbox_dispencer",
	"atrium_gate",
	"atrium_idol",
	"atrium_overgrowth",
	"atrium_light",
	"atrium_rubble",
	"atrium_statue",
	"atrium_statue_facing",
	"nightmarelight",
	"nightmaregrowth",
	"minotaurchest",
	"pandoraschest",
	"sacred_chest",
	"ruins_statue_mage",
	"ruins_statue_mage_nogem",
	"ruins_statue_head",
	"ruins_statue_head_nogem",
--古代家具
	"ruins_bowl",
	"ruins_chair",
	"ruins_chipbowl",
	"ruins_plate",
	"ruins_rubble_chair",
	"ruins_rubble_table",
	"ruins_rubble_vase",
--地形
	"cave_hole",
--发条残骸
	"chessjunk",
	"chessjunk1",
	"chessjunk2",
	"chessjunk3",
--生成点
	"chessjunk_spawner",
--雕像
	"archive_moon_statue",
	"archive_rune_statue",
}