return {
--航海工具
	"oar",
	"oar_driftwood",
	"malbatross_beak",
	"mast_item",
	"mast_malbatross_item",
	"anchor_item",
	"steeringwheel_item",
	"boatpatch",
	"boat_item",
--采集工具
	"axe",
	"goldenaxe",
	"moonglassaxe",
	"lucy",
	"pickaxe",
	"goldenpickaxe",
	"multitool_axe_pickaxe",
	"shovel",
	"goldenshovel",
--装修工具
	"hammer",
	"pitchfork",
--刮毛工具
	"razor",
--书写工具
	"featherpencil",
--训牛工具
	"brush",
	"saddle_basic",
	"saddle_race",
	"saddle_war",
	"saddlehorn",
--训练工具
	"yotc_carrat_scale_item",
	"yotc_carrat_gym_speed_item",
	"yotc_carrat_gym_reaction_item",
	"yotc_carrat_gym_stamina_item",
	"yotc_carrat_gym_direction_item",
	"yotc_carrat_race_start_item",
	"yotc_carrat_race_checkpoint_item",
	"yotc_carrat_race_finish_item",
--烹饪工具
	"portablecookpot_item",
	"portableblender_item",
	"portablespicer_item",
--施肥工具
	"fertilizer",
--照明工具
	"torch",
	"lighter",
	"pumpkin_lantern",
	"redlantern",
	"lantern",
	"miniboatlantern",
	"minerhat",
	"molehat",
--降温灭火工具
	"waterballoon",
	"featherfan",
	"perdfan",
--狩猎工具
	"birdtrap",
	"trap",
	"bugnet",
	"fishingnet",
	"fishingrod",
	"oceanfishingrod",
	"oceanfishinglure_spinner_red",
	"oceanfishinglure_spinner_green",
	"oceanfishinglure_spinner_blue",
	"oceanfishinglure_spoon_red",
	"oceanfishinglure_spoon_green",
	"oceanfishinglure_spoon_blue",
	"oceanfishingbobber_ball",
	"oceanfishingbobber_oval",
	"oceanfishingbobber_crow",
	"oceanfishingbobber_robin",
	"oceanfishingbobber_robin_winter",
	"oceanfishingbobber_canary",
	"oceanfishingbobber_goose",
	"oceanfishingbobber_malbatross",
--称重工具
	"pocket_scale",
--降温避雨工具
	"minifan",
	"grass_umbrella",
	"umbrella",
--地图工具
	"compass",
	"miniflare",
--打包工具
	"giftwrap",
	"bundlewrap",
--缝纫工具
	"sewing_kit",
	"sewing_tape",
--过夜工具
	"bedroll_straw",
	"bedroll_furry",
--保温工具
	"heatrock",

}