return {
--墙体
	"wall_hay",
	"brokenwall_hay",
	"wall_wood",
	"brokenwall_wood",
	"wall_stone",
	"brokenwall_stone",
	"wall_ruins",
	"brokenwall_ruins",
	"wall_moonrock",
	"brokenwall_moonrock",
--围栏
	"fence",
	"fence_gate",
--放牧
	"saltlick",
--火堆
	"campfire",
	"firepit",
	"coldfire",
	"coldfirepit",
	"nightlight",
--照明
	"mushroom_light",
	"mushroom_light2",
--过夜
	"tent",
	"siestahut",
	"portabletent",
--农场
	"slow_farmplot",
	"fast_farmplot",
	"mushroom_farm",
--蜂箱
	"beebox",
--晒肉
	"meatrack",
--烹饪
	"cookpot",
	"portablecookpot",
	"portableblender",
	"portablespicer",
--保鲜
	"icebox",
	"saltbox",
	"fish_box",
	"trophyscale_fish",
--冬季盛宴
	"table_winters_feast",
	"wintersfeastoven",
--气象
	"winterometer",
	"rainometer",
	"lightning_rod",
--灭火
	"firesuppressor",
--标记
	"minisign",
	"homesign",
	"arrowsign_post",
--储存
	"treasurechest",
	"dragonflychest",
--取暖
	"dragonflyfurnace",
--换装
	"wardrobe",
--稻草人
	"scarecrow",
--鸟笼
	"birdcage",
--复活
	"resurrectionstatue",
--魔法
	"telebase",
	"sentryward",
	"moondial",
	"townportal",
	"eyeturret",
--薇诺娜
	"winona_battery_high",
	"winona_battery_low",
	"winona_catapult",
	"winona_spotlight",
--温蒂
	"sisturn",
--航海
	"boat",
	"steeringwheel",
	"anchor",
	"mast",
	"mast_malbatross",
	"winch",
	"waterpump",
--科技
	"researchlab",
	"researchlab2",
	"cartographydesk",
	"sculptingtable",
	"madscience_lab",
	"seafaring_prototyper",
	"tacklestation",
	"researchlab4",
	"researchlab3",
--祭坛
	"ancient_altar_broken",
	"ancient_altar",
	"moon_altar",
	"moon_altar_cosmic",
	"perdshrine",
	"wargshrine",
	"pigshrine",
	"yotc_carratshrine",
--萝卜鼠
	"yotc_carrat_scale",
	"yotc_carrat_gym_speed",
	"yotc_carrat_gym_reaction",
	"yotc_carrat_gym_stamina",
	"yotc_carrat_gym_direction",
	"yotc_carrat_race_start",
	"yotc_carrat_race_checkpoint",
	"yotc_carrat_race_finish",
--装饰
	"endtable",
	"succulent_potted",
	"pottedfern",
	"winter_treestand",
--古代家具
	"ruinsrelic_plate",
	"ruinsrelic_chipbowl",
	"ruinsrelic_bowl",
	"ruinsrelic_vase",
	"ruinsrelic_chair",
	"ruinsrelic_table",
--隐士小岛
	"beebox_hermit",
	"meatrack_hermit",
}