return {
--prefab名称转换，以匹配贴图xml中现成可用的图片名称
	prefablist = {
--发条雕像
	["sculpture_bishopbody"] = "sculpture_bishopbody_full",
	["sculpture_knightbody"] = "sculpture_knightbody_full",
	["sculpture_rookbody"] = "sculpture_rookbody_full",

--宠物
		["critter_dragonling"] = "critter_dragonling_builder",
		["critter_glomling"] = "critter_glomling_builder",
		["critter_kitten"] = "critter_kitten_builder",
		["critter_lamb"] = "critter_lamb_builder",
		["critter_perdling"] = "critter_perdling_builder",
		["critter_puppy"] = "critter_puppy_builder",
		["critter_lunarmothling"] = "critter_lunarmothling_builder",
--麦斯威尔的阴影
		["shadowdigger"] = "shadowdigger_builder",
		["shadowduelist"] = "shadowduelist_builder",
		["shadowlumber"] = "shadowlumber_builder",
		["shadowminer"] = "shadowminer_builder",
--麦斯威尔的雕像
		["statuemaxwell"] = "statue",
--丘比特雕像
		["statueharp"] = "statue_small",
--迷你指示牌
		["minisign"] = "minisign_drawn",
--圣诞树
		["winter_tree"] = "winter_treestand",

		["wormhole_limited_1"] = "wormhole_sick",
		["oasislake"] = "oasis",
		["resurrectionstone"] = "resurrection_stone",
		["moon_altar_rock_idol"] = "moon_altar_idol_rock",
		["moon_altar_rock_glass"] = "moon_altar_glass_rock",
		["moon_altar_rock_seed"] = "moon_altar_seed_rock",
		["gravestone"] = "gravestones",
		["eyeturret"] = "eyeball_turret",
		["mermthrone"] = "merm_king_carpet",
		
		["deciduoustree_burnt"] = "tree_leaf_burnt",
		["deciduoustree_stump"] = "tree_leaf_stump",
 	},
--prefab名称赋值，以匹配对应文本字符串。
	desclist = {
--雕像
		["sculpture_bishopbody_full"] = STRINGS.NAMES.SCULPTURE_BISHOPBODY,
		["sculpture_knightbody_full"] = STRINGS.NAMES.SCULPTURE_KNIGHTBODY,
		["sculpture_rookbody_full"] = STRINGS.NAMES.SCULPTURE_ROOKBODY,
		["statue"] = STRINGS.NAMES.STATUEMAXWELL,
		["statue_small"] = STRINGS.NAMES.STATUEHARP,
--桦树
		["tree_leaf_burnt"] = STRINGS.NAMES.DECIDUOUSTREE,
		["tree_leaf_stump"] = STRINGS.NAMES.DECIDUOUSTREE,
--复活骨架
		["stalker_forest"] = STRINGS.NAMES.STALKER,
--绿洲湖泊
		["oasis"] = STRINGS.NAMES.OASISLAKE,
--试金石
		["resurrection_stone"] = STRINGS.NAMES.RESURRECTIONSTONE,
--天梯祭坛零件
		["moon_altar_glass_rock"] = STRINGS.NAMES.MOON_ALTAR_ROCK_GLASS,
		["moon_altar_idol_rock"] = STRINGS.NAMES.MOON_ALTAR_ROCK_IDOL,
		["moon_altar_seed_rock"] = STRINGS.NAMES.MOON_ALTAR_ROCK_SEED,
--生病的虫洞
		["wormhole_sick"] = STRINGS.NAMES.WORMHOLE_LIMITED,
--墓碑
		["gravestones"] = STRINGS.NAMES.GRAVESTONE,
--眼球塔
		["eyeball_turret"] = STRINGS.NAMES.EYETURRET,
--编织的暗影
		["stalker_minion1"] = STRINGS.NAMES.STALKER_MINION,
		["stalker_minion2"] = STRINGS.NAMES.STALKER_MINION,
--鱼人王地毯
		["merm_king_carpet"] = STRINGS.NAMES.MERMTHRONE,
--玻璃制品
		["glassspike_short"] = STRINGS.NAMES.GLASSSPIKE,
		["glassspike_med"] = STRINGS.NAMES.GLASSSPIKE,
		["glassspike_tall"] = STRINGS.NAMES.GLASSSPIKE,
--多枝的树
		["twiggy_short"] = STRINGS.NAMES.TWIGGYTREE,
		["twiggy_normal"] = STRINGS.NAMES.TWIGGYTREE,
		["twiggy_tall"] = STRINGS.NAMES.TWIGGYTREE,
		["twiggy_old"] = STRINGS.NAMES.TWIGGYTREE,
--荧光草
		["flower_cave_double"] = STRINGS.NAMES.FLOWER_CAVE,
		["flower_cave_triple"] = STRINGS.NAMES.FLOWER_CAVE,
--月树
		["moon_tree_normal"] = STRINGS.NAMES.MOON_TREE,
		["moon_tree_tall"] = STRINGS.NAMES.MOON_TREE,
		["moon_tree_short"] = STRINGS.NAMES.MOON_TREE,
--花
		["flower_rose"] = STRINGS.NAMES.FLOWER,
		["planted_flower"] = STRINGS.NAMES.FLOWER,
--常青树
		["evergreen_short"] = STRINGS.NAMES.EVERGREEN,
		["evergreen_normal"] = STRINGS.NAMES.EVERGREEN,
		["evergreen_tall"] = STRINGS.NAMES.EVERGREEN,
		["evergreen_stump"] = STRINGS.NAMES.EVERGREEN,
		["evergreen_burnt"] = STRINGS.NAMES.EVERGREEN,
--粗壮常青树
		["evergreen_sparse_short"] = STRINGS.NAMES.EVERGREEN_SPARSE,
		["evergreen_sparse_normal"] = STRINGS.NAMES.EVERGREEN_SPARSE,
		["evergreen_sparse_tall"] = STRINGS.NAMES.EVERGREEN_SPARSE,
		["evergreen_sparse_stump"] = STRINGS.NAMES.EVERGREEN_SPARSE,
--桦树
		["deciduoustree_short"] = STRINGS.NAMES.DECIDUOUSTREE,
		["deciduoustree_normal"] = STRINGS.NAMES.DECIDUOUSTREE,
		["deciduoustree_tall"] = STRINGS.NAMES.DECIDUOUSTREE,
		["deciduoustree_stump"] = STRINGS.NAMES.DECIDUOUSTREE,
		["deciduoustree_burnt"] = STRINGS.NAMES.DECIDUOUSTREE,
--完全正常的树
		["livingtree_halloween"] = STRINGS.NAMES.LIVINGTREE,
--树苗
		["sapling_moon"] = STRINGS.NAMES.SAPLING,
--仙人掌
		["oasis_cactus"] = STRINGS.NAMES.CACTUS,
--石化树
		["rock_petrified_tree_short"] = STRINGS.NAMES.ROCK_PETRIFIED_TREE,
		["rock_petrified_tree_med"] = STRINGS.NAMES.ROCK_PETRIFIED_TREE,
		["rock_petrified_tree_tall"] = STRINGS.NAMES.ROCK_PETRIFIED_TREE,
		["rock_petrified_tree_old"] = STRINGS.NAMES.ROCK_PETRIFIED_TREE,
--石果灌木
		["rock_avocado_fruit_sprout_sapling"] = STRINGS.NAMES.ROCK_AVOCADO_FRUIT_SPROUT,
--鹿角
		["deer_antler1"] = STRINGS.NAMES.DEER_ANTLER,
		["deer_antler2"] = STRINGS.NAMES.DEER_ANTLER,
		["deer_antler3"] = STRINGS.NAMES.DEER_ANTLER,
--沃利的厨具
		["portablecookpot"] = STRINGS.NAMES.PORTABLECOOKPOT_ITEM,
		["portableblender"] = STRINGS.NAMES.PORTABLEBLENDER_ITEM,
		["portablespicer"] = STRINGS.NAMES.PORTABLESPICER_ITEM,
--墙体
		["brokenwall_hay"] = STRINGS.NAMES.WALL_HAY,
		["brokenwall_wood"] = STRINGS.NAMES.WALL_WOOD,
		["brokenwall_stone"] = STRINGS.NAMES.WALL_STONE,
		["brokenwall_ruins"] = STRINGS.NAMES.WALL_RUINS,
		["brokenwall_moonrock"] = STRINGS.NAMES.WALL_MOONROCK,

		["minisign"] = STRINGS.NAMES.MINISIGN,
		["moose"] = STRINGS.NAMES.MOOSE2,
		["mooseegg"] = STRINGS.NAMES.MOOSEEGG2,
		["ruins_bowl"] = STRINGS.NAMES.RELIC.." bowl",
		["ruins_chair"] = STRINGS.NAMES.RELIC.." chair",
		["ruins_chipbowl"] = STRINGS.NAMES.RELIC.." chipbowl",
		["ruins_plate"] = STRINGS.NAMES.RELIC.." plate",
		["ruins_statue_head"] = STRINGS.NAMES.ANCIENT_STATUE,
		["ruins_statue_head_nogem"] = STRINGS.NAMES.ANCIENT_STATUE,
		["ruins_statue_mage"] = STRINGS.NAMES.ANCIENT_STATUE,
		["ruins_statue_mage_nogem"] = STRINGS.NAMES.ANCIENT_STATUE,
		["ruins_table"] = STRINGS.NAMES.RELIC.." table",
		["ruins_vase"] = STRINGS.NAMES.RELIC.." vase",
		["sculpture_bishop"] = STRINGS.NAMES.SCULPTURE_BISHOPBODY,
		["sculpture_knight"] = STRINGS.NAMES.SCULPTURE_KNIGHTBODY,
		["sculpture_rook"] = STRINGS.NAMES.SCULPTURE_ROOKBODY,
		["spiderden_2"] = STRINGS.NAMES.SPIDERDEN,
		["spiderden_3"] = STRINGS.NAMES.SPIDERDEN,
		["spiderhole_rock"] = STRINGS.NAMES.SPIDERHOLE,
		["winter_tree"] = STRINGS.NAMES.WINTER_TREE,
		["moonhound"] = STRINGS.NAMES.HOUND,
		["moonpig"] = STRINGS.NAMES.PIGMAN,
	},
	showimagelist = {
		["arrowsign_panel"] = true,
		["arrowsign_post"] = true,
		["bat"] = true,
		["bee"] = true,
		["beebox"] = true,
		["birdcage"] = true,
		["bundle"] = true,
		["butterfly"] = true,
		["campfire"] = true,
		["canary"] = true,
		["cartographydesk"] = true,
		["chesspiece_bishop"] = true,
		["chesspiece_bishop_marble"] = true,
		["chesspiece_bishop_stone"] = true,
		["chesspiece_formal"] = true,
		["chesspiece_formal_marble"] = true,
		["chesspiece_formal_stone"] = true,
		["chesspiece_hornucopia"] = true,
		["chesspiece_hornucopia_marble"] = true,
		["chesspiece_hornucopia_stone"] = true,
		["chesspiece_knight"] = true,
		["chesspiece_knight_marble"] = true,
		["chesspiece_knight_stone"] = true,
		["chesspiece_muse"] = true,
		["chesspiece_muse_marble"] = true,
		["chesspiece_muse_stone"] = true,
		["chesspiece_pawn"] = true,
		["chesspiece_pawn_marble"] = true,
		["chesspiece_pawn_stone"] = true,
		["chesspiece_pipe"] = true,
		["chesspiece_pipe_marble"] = true,
		["chesspiece_pipe_stone"] = true,
		["chesspiece_rook"] = true,
		["chesspiece_rook_marble"] = true,
		["chesspiece_rook_stone"] = true,
		["coldfire"] = true,
		["coldfirepit"] = true,
		["cookpot"] = true,
		["crow"] = true,
		["dragonflychest"] = true,
		["dragonflyfurnace"] = true,
		["endtable"] = true,
		["fast_farmplot"] = true,
		["firepit"] = true,
		["firesuppressor"] = true,
		["gift"] = true,
		["homesign"] = true,
		["icebox"] = true,
		["killerbee"] = true,
		["lightning_rod"] = true,
		["meatrack"] = true,
		["minisign_drawn"] = true,
		["mole"] = true,
		["moondial"] = true,
		["mosquito"] = true,
		["mushroom_farm"] = true,
		["mushroom_light"] = true,
		["mushroom_light2"] = true,
		["nightlight"] = true,
		["perdshrine"] = true,
		["rabbit"] = true,
		["rabbithouse"] = true,
		["rainometer"] = true,
		["researchlab"] = true,
		["researchlab2"] = true,
		["researchlab3"] = true,
		["researchlab4"] = true,
		["resurrectionstatue"] = true,
		["robin"] = true,
		["robin_winter"] = true,
		["saltlick"] = true,
		["scarecrow"] = true,
		["sculptingtable"] = true,
		["sculpture_bishophead"] = true,
		["sculpture_knighthead"] = true,
		["sculpture_rooknose"] = true,
		["sentryward"] = true,
		["siestahut"] = true,
		["sketch"] = true,
		["slow_farmplot"] = true,
		["slurper"] = true,
		["snowball"] = true,
		["telebase"] = true,
		["teleportato_base"] = true,
		["tent"] = true,
		["treasurechest"] = true,
		["wardrobe"] = true,
		["webber"] = true,
		["wendy"] = true,
		["wes"] = true,
		["wickerbottom"] = true,
		["willow"] = true,
		["wilson"] = true,
		["winterometer"] = true,
		["wolfgang"] = true,
		["woodie"] = true,
		["wx78"] = true,
	},
}