return {
--标志性地点
	"pigking",
	"critterlab",
	"moonbase",
	"stagehand",
--领地标记
	"pighead",
	"mermhead",
--复活
	"resurrectionstone",
--传送门
	"multiplayer_portal_moonrock",
	"migration_portal",
--池塘
	"oasislake",
	"pond",
	"pond_mos",
	"pond_cave",
	"lava_pond",
	"hotspring",
--玄武岩
	"basalt",
	"basalt_pillar",
--天体
	"moon_altar_rock_glass",
	"moon_altar_rock_idol",
	"moon_altar_rock_seed",
--浮木
	"driftwood_small1",
	"driftwood_small2",
	"driftwood_tall",
--骨架
	"dead_sea_bones",
	"houndbone",
	"fossil_stalker",
	"skeleton",
	"skeleton_player",
	"scorched_skeleton",
--坟墓
	"mound",
	"gravestone",
--装饰
	"lava_pond_rock",
	"lava_pond_rock2",
	"lava_pond_rock3",
	"lava_pond_rock4",
	"lava_pond_rock5",
	"lava_pond_rock6",
	"lava_pond_rock7",
	"moose_nesting_ground",
--虫洞
	"wormhole",
	"wormhole_limited_1",
	
}